### ISSUE TITLE
Using my own dataset without Jester

### ISSUE THREAD

**Issue by atheeraa** [floriandotpy/20bn-realtimenet#3]
Hello,

Could you please tell me if I can use your implementation with my dataset without using Jester? 

I can't seem to find it, the link shows that the website is down.

**Comment by floriandotpy** [comment]
The original website is down because TwentyBN has been acquired by Qualcomm.

This repo here is just an outdated fork. Originally, the repository was called `20bn-realtimenet`, but it was renamed to `sense` a while back. The original (and official) repo is now hosted at: https://github.com/quic/sense
You'd best ask your question there.

**Comment by atheeraa** [comment]
Thank you for your reply, is there a way I could get the pretrained ckpt files from you? 
I've been searching everywhere but couldn't find a solution.
